#Create a user 

POST http://localhost:3000/users 
Content-Type: application:json

  {
    "username": "ahamdogo",
    "email": "ahmadogo413@gmail.com",
    "password":"Ahmad@413",
    "walletAddress": "0x1234567890abcdef1234567890abcdef1234567890"
  }